export const ROLES = {
  SUPER_ADMIN: "super-admin",
  ADMIN: "admin",
  BUSINESS_OWNER: "business-owner",
  PROJECT_MANAGER: "project-manager",
  DESIGNER: "designer",
  QAS: "qas",
  FINANCE: "finance",
  SUBCONTRACTOR: "subcontractor",
  CLIENT: "client",
  SALES: "sales",
  EMPLOYEE: "employee",
};

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: "Super Admin",
  [ROLES.ADMIN]: "Admin",
  [ROLES.BUSINESS_OWNER]: "Business Owner",
  [ROLES.PROJECT_MANAGER]: "Project Manager",
  [ROLES.DESIGNER]: "Designer",
  [ROLES.QAS]: "QAS",
  [ROLES.FINANCE]: "Finance",
  [ROLES.SUBCONTRACTOR]: "Subcontractor",
  [ROLES.CLIENT]: "Client",
  [ROLES.SALES]: "Sales",
  [ROLES.EMPLOYEE]: "Employee",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ["*"],
  [ROLES.ADMIN]: [
    "users.read",
    "users.write",
    "projects.read",
    "projects.write",
    "reports.read",
    "settings.read",
    "settings.write",
  ],
  [ROLES.BUSINESS_OWNER]: [
    "projects.read",
    "projects.write",
    "finance.read",
    "reports.read",
    "settings.read",
  ],
  [ROLES.PROJECT_MANAGER]: [
    "projects.read",
    "projects.write",
    "tasks.read",
    "tasks.write",
    "team.read",
    "reports.read",
  ],
  [ROLES.DESIGNER]: [
    "projects.read",
    "tasks.read",
    "tasks.write",
    "designs.read",
    "designs.write",
  ],
  [ROLES.QAS]: [
    "projects.read",
    "tasks.read",
    "tasks.write",
    "quality.read",
    "quality.write",
  ],
  [ROLES.FINANCE]: [
    "finance.read",
    "finance.write",
    "invoices.read",
    "invoices.write",
    "reports.read",
  ],
  [ROLES.SUBCONTRACTOR]: [
    "tasks.read",
    "tasks.write",
    "documents.read",
    "documents.write",
  ],
  [ROLES.CLIENT]: [
    "projects.read",
    "documents.read",
    "invoices.read",
    "communications.read",
    "communications.write",
  ],
  [ROLES.SALES]: [
    "leads.read",
    "leads.write",
    "clients.read",
    "clients.write",
    "proposals.read",
    "proposals.write",
  ],
  [ROLES.EMPLOYEE]: [
    "projects.read",
    "tasks.read",
    "tasks.write",
  ],
};
