export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  SUPER_ADMIN: {
    DASHBOARD: "/super-admin",
    TENANTS: "/super-admin/tenants",
    TENANTS_CREATE: "/super-admin/tenants/new",
    TENANT_DETAIL: "/super-admin/tenants/:tenantId",
    PLANS: "/super-admin/plans",
    USERS: "/super-admin/users",
    PERMISSIONS: "/super-admin/permissions",
    REPORTS: "/super-admin/reports",
    SITE_VISITS: "/super-admin/site-visits",
    SITE_VISIT_SCHEDULE: "/super-admin/site-visits/schedule",
    SITE_VISIT_REPORT: "/super-admin/site-visits/:visitId/report",
    SETTINGS: "/super-admin/settings",
    AUDIT_LOG: "/super-admin/audit-log",
    ORGANIZATIONS: "/super-admin/organizations",
  },
  ADMIN: {
    DASHBOARD: "/admin",
    PIPELINE: "/admin/pipeline",
    LEADS_LIST: "/admin/leads",
    LEADS_NEW: "/admin/leads/new",
    LEADS_QUALIFIED: "/admin/leads/qualified",
    LEAD_DETAIL: "/admin/leads/:leadId",
    FOLLOW_UPS: "/admin/follow-ups",
    FOLLOW_UP_DETAIL: "/admin/follow-ups/:followUpId",
    LEAD_SOURCES: "/admin/lead-sources",
    CLIENT_CONVERSION: "/admin/client-conversion",
    CLIENT_DETAIL: "/admin/clients/:clientId",
    ACTIVITY_LOGS: "/admin/activity-logs",
    NOTIFICATIONS: "/admin/notifications",
    PROPOSALS: "/admin/proposals",
    NEGOTIATIONS: "/admin/negotiations",
    PAYMENTS: "/admin/payments",
    CRM_ANALYTICS: "/admin/crm-analytics",
    TEAM_PERFORMANCE: "/admin/team-performance",
    LOST_LEADS: "/admin/lost-leads",
    WON_PROJECTS: "/admin/won-projects",
    SITE_VISITS: "/admin/site-visits",
    SITE_VISIT_SCHEDULE: "/admin/site-visits/schedule",
    SITE_VISIT_REPORT: "/admin/site-visits/:visitId/report",
    USERS: "/admin/users",
    PROJECTS: "/admin/projects",
    REPORTS: "/admin/reports",
    SETTINGS: "/admin/settings",
  },
  BUSINESS_OWNER: {
    DASHBOARD: "/business-owner",
    PROJECTS: "/business-owner/projects",
    FINANCE: "/business-owner/finance",
    REPORTS: "/business-owner/reports",
    SETTINGS: "/business-owner/settings",
  },
  PROJECT_MANAGER: {
    DASHBOARD: "/project-manager",
    PROJECTS: "/project-manager/projects",
    TASKS: "/project-manager/tasks",
    TEAM: "/project-manager/team",
    REPORTS: "/project-manager/reports",
  },
  DESIGNER: {
    DASHBOARD: "/designer",
    PROJECTS: "/designer/projects",
    TASKS: "/designer/tasks",
    DESIGNS: "/designer/designs",
  },
  QAS: {
    DASHBOARD: "/qas",
    PROJECTS: "/qas/projects",
    TASKS: "/qas/tasks",
    INSPECTIONS: "/qas/inspections",
    REPORTS: "/qas/reports",
  },
  FINANCE: {
    DASHBOARD: "/finance",
    INVOICES: "/finance/invoices",
    PAYMENTS: "/finance/payments",
    BUDGETS: "/finance/budgets",
    REPORTS: "/finance/reports",
  },
  SUBCONTRACTOR: {
    DASHBOARD: "/subcontractor",
    TASKS: "/subcontractor/tasks",
    DOCUMENTS: "/subcontractor/documents",
    PAYMENTS: "/subcontractor/payments",
  },
  CLIENT: {
    DASHBOARD: "/client",
    PROJECTS: "/client/projects",
    DOCUMENTS: "/client/documents",
    INVOICES: "/client/invoices",
    COMMUNICATIONS: "/client/communications",
  },
  SALES: {
    DASHBOARD: "/sales",
    LEADS: "/sales/leads",
    CLIENTS: "/sales/clients",
    PROPOSALS: "/sales/proposals",
    REPORTS: "/sales/reports",
  },
};
